swagger: '2.0'
info:
 title: Event Management API
 description: API to manage event tickets and accounts
 version: '1.0'
host: sse-project-gateway.us-central1.gateway.dev
schemes:
 - https
paths:
  /create_account:
    post:
      summary: Create a new account
      operationId: createAccount
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_create_account
      responses:
        '201':
          description: Account created successfully

  /delete_account:
    post:
      summary: Delete an account
      operationId: deleteAccount
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_delete_account
      responses:
        '201':
          description: Account deleted successfully
  
  /update_account:
    post:
      summary: Update an account
      operationId: updateAccount
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_update_account
      responses:
        '201':
          description: Account updated successfully
  
  /get_account_info:
    get:
      summary: Get account info
      operationId: getAccountInfo
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_account_info
      responses:
        '201':
          description: Account info retrieved successfully
   
  /create_event:
    post:
      summary: Create a new event
      operationId: createEvent
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_create_event
      responses:
        '201':
          description: Event created successfully

  /delete_event:
    post:
      summary: Delete an event
      operationId: deleteEvent
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_delete_event
      responses:
        '201':
          description: Event deleted successfully
    
  /get_event_info:
    get:
      summary: Get event info
      operationId: getEventInfo
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_event_info
      responses:
        '201':
          description: Event info retrieved successfully

  /get_events_for_attendee:
    get:
      summary: Get events for attendee
      operationId: getEventsForAttendee
      parameters:
        - in: query
          name: identifier
          type: string
          required: true
          description: The name of the attendee to retrieve events for.
        - in: query
          name: object_type
          type: string
          required: true
          description: The type of object being queried.
        - in: query
          name: function
          type: string
          required: true
          description: The function to apply to the retrieved data.
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_events_for_attendee
      responses:
        '201':
          description: Events retrieved successfully

  /get_events_for_artist:
    get:
      summary: Get events for artist
      operationId: getEventsForArtist
      parameters:
        - in: query
          name: identifier
          type: string
          required: true
          description: The name of the artist to retrieve events from.
        - in: query
          name: object_type
          type: string
          required: true
          description: The type of object being queried.
        - in: query
          name: function
          type: string
          required: true
          description: The function to apply to the retrieved data.
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_events_for_artist
      responses:
        '201':
          description: Events retrieved successfully

  /get_events_for_venue:
    get:
      summary: Get events for venue
      operationId: getEventsForVenue
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_events_for_venue
      responses:
        '201':
          description: Events retrieved successfully


  /get_cities_by_country:
    get:
      summary: Get cities by country
      operationId: getCitiesByCountry
      parameters:
        - in: query
          name: country
          type: string
          required: true
          description: The name of the country to retrieve cities from.
        - in: query
          name: object_type
          type: string
          required: true
          description: The type of object being queried.
        - in: query
          name: function
          type: string
          required: true
          description: The function to apply to the retrieved data.
      responses:
        '201':
          description: Cities retrieved successfully
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_cities_by_country

  /get_events_in_city:
    post:
      summary: Get events in city
      operationId: getEventsInCity
      responses:
        '201':
          description: Events retrieved successfully
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_events_in_city

  /check_email_in_use: 
    post:
      summary: Check an email is in use
      operationId: checkEmailInUse
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_check_email_in_use
      responses:
        '201':
          description: Event deleted successfully

  /purchase_ticket:
    post:
      summary: Purchase a ticket
      operationId: purchaseTicket
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_purchase_ticket
      responses:
        '201':
          description: Ticket purchased successfully

  /get_tickets_info:
      get:
        summary: Get tickets info
        operationId: getTicketInfo
        x-google-backend:
          address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_tickets_info
        responses:
          '201':
            description: Tickets info retrieved successfully
  
  /get_tickets_info_for_users:
    get:
      summary: Get tickets info for users
      operationId: getTicketInfoForUsers
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_get_tickets_info_for_users
      responses:
        '201':
          description: Tickets info for user retrieved successfully

  /assign_tickets_to_attendee:
    post:
      summary: Assigns tickets to attendee
      operationId: assignTicketsToAttendee
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_assign_tickets_to_attendee
      responses:
        '201':
          description: ticket assigned successful 

  /delete_expired_tickets:
    post:
      summary: Delete expired tickets
      operationId: deleteExpiredTickets
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_delete_expired_tickets
      responses:
        '201':
          description: Deleted expired tickets successfully
  
  /update_tickets_redeemed_status:
    post:
      summary: Update tickets redeemed status
      operationId: updateTicketsRedeemedStatus
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_update_tickets_redeemed_status
      responses:
        '201':
          description: Update tickets redeemed status successfully


  /create_tickets:
    post:
      summary: Create tickets
      operationId: createTickets
      x-google-backend:
        address: https://us-central1-still-descent-414311.cloudfunctions.net/api_create_tickets
      responses:
        '201':
          description: Created tickets successfully


securityDefinitions:
 your_custom_auth_id:
   authorizationUrl: ""
   flow: "implicit"
   type: "oauth2"
   # The value below should be unique
   x-google-issuer: "https://accounts.google.com"
   x-google-jwks_uri: "https://www.googleapis.com/oauth2/v1/certs"
   x-google-audiences: "https://see-project-gateway-c4vspufr.uc.gateway.dev"

security:
- your_custom_auth_id: []
